#!/bin/bash

echo Please enter file name of forward read. Do not include file extension:

read R1

echo Please enter file name of the reverse read. Do not include file extension:

read R2

echo please enter the name of your future bam file. Do not include file extension:

read filename

/home/ed/src/chicago/fq-jt -f $R1.fastq.gz | gzip > $R1.trimmed.fastq.gz

/home/ed/src/chicago/fq-jt -f $R2.fastq.gz | gzip > $R2.trimmed.fastq.gz

bwa mem -SP5M -t 6 /scratch1/rachel/hs37d5.fa $R1.trimmed.fastq.gz $R2.trimmed.fastq.gz | samtools view -bhS -@ 6 - > $filename.output.bam

samtools sort -o $filename.sorted.qname.bam -n $filename.output.bam 

samtools view -h $filename.sorted.qname.bam | pairtools parse -c /scratch1/rachel/chrom.size -o $filename.parsed.pairsam.gz
   
pairtools sort --nproc 6 -o $filename.sorted.pairsam.gz $filename.parsed.pairsam.gz
