#!/bin/bash

echo Please enter file name of the first file.

read in1

echo Please enter file name of the second file.

read in2

echo please enter the name of your future merged file. Do not include file extension:

read filename

pairtools merge -o $filename.sorted.pairsam.gz $in2.sorted.pairsam.gz  $in1.sorted.pairsam.gz  2>> log1.txt

pairtools dedup --nproc-in 6 --mark-dups -o $filename.dedup.pairsam.gz $filename.sorted.pairsam.gz 2>> log2.txt

pairtools select  '(pair_type == "UU") or (pair_type == "UR") or (pair_type == "RU")' -o $filename.filtered.pairsam.gz $filename.dedup.pairsam.gz 2>> log3.txt

pairtools split --output-pairs $filename.output.pairs.gz $filename.filtered.pairsam.gz 2>> log4.txt

pairix -f $filename.output.pairs.gz 2>> log5.txt

cooler cload pairix /scratch1/rachel/chrom.size:10000 $filename.output.pairs.gz $filename.res.10000.cool 2>> log6.txt

cooler cload pairix /scratch1/rachel/chrom.size:5000 $filename.output.pairs.gz $filename.res.5000.cool 2>> log7.txt

cooler balance $filename.res.10000.cool 

cooler balance $filename.res.5000.cool 

cooler zoomify $filename.res.10000.cool 

cooler zoomify $filename.res.5000.cool
